- name: Example of conditional takss
  hosts: all
  become: true
  gather_facts: true
  tasks:
          - name: install  vsftpd   only redhat 7  or centos 8
            yum:
                    name: httpd
                    state: installed
            when: > 
                 ( ansible_distribution == 'RedHat' and ansible_distribution_version == '7.5')
                 or ( ansible_distribution == 'Fedora' and  ansible_distribution_version == '8.6')


