- name: Example of Template file
  hosts: all
  gather_facts: true
  become: true
  tasks:
          - name: copy  jina2 file
            template:
                    src: test.j2
                    dest: /etc/myhosts
