- name: Example of List of has Loop
  hosts: all
  become: true
  vars:
          myusers:
                  - username: ravi
                    pw: redhat
                    grp: staff

                  - username: shyam
                    pw: fedora
                    grp: guests

                  - username: ram
                    pw: centos
                    grp: manager
  tasks:
          - name: first add three groups
            group:
                   name: "{{ item }}"
                   state: present
            with_items:
                    - staff
                    - guests
                    - manager



          - name: add user  into different group with password
            user:
                    name: "{{ item.username }}"
                    password: "{{ item.pw | password_hash('sha512') }}"
                    group: "{{ item.grp }}"
            with_items: "{{ myusers }}"
