- name: Example of List of has Loop
  hosts: all
  become: true
  tasks:
          - name: first add three groups
            group:
                   name: "{{ item }}"
                   state: present
            with_items:
                    - staff
                    - guests
                    - manager



          - name: add user  into different group with password
            user:
                    name: "{{ item.username }}"
                    password: "{{ item.pw | password_hash('sha512') }}"
                    group: "{{ item.grp }}"
            with_items:
                    - { username: 'ram', pw: 'redhat', grp: 'staff' }
                    - { username: 'manish', pw: 'fodora', grp: 'guests' }
                    - { username: 'shyam', pw: 'centos', grp: 'manager' }
