- name: Example of Simple Loop
  hosts: all
  become: true
  tasks:
           - name: Install ftp http vsftpd
             yum:
                     name: 
                       - httpd
                       - ftp
                       - vsftpd
                     state: installed


           



           - name: Install ftp http vsftpd
             yum:
                     name:  "{{ item }}"
                     state: installed
             with_items:
                     - vsftpd
                     - ftp
                     - httpd


           



