- name: Example of tags
  hosts: all
  become: true
  tasks:
          - name: Install httpd
            yum:
                    name: httpd
                    state: installed
            tags: install


          - name: UnInstall httpd
            yum:
                  name: httpd
                  state: absent 
