- name: Example of  Playbook level variale
  hosts: all
  become: true
  tasks:
          - name: Import  vars file
            include_vars: /home/ec2-user/chapter-4/test.yml

          - name: Install the pckage
            yum:
                    name: "{{webpkg}}"
                    state: installed




          - name: Create  "{{ webroot }}"
            file:
                    path: "{{ webroot }}"
                    state: directory


          - name: Create index.html page inside  "{{ webroot }}"
            copy:
                    content: "hellworld"
                    dest: "{{ webroot }}/index.html"


          - name: Start apache service
            service:
                   name: "{{ webpkg }}"
                   state: started
                   enabled: true
