- hosts: all
  become: true
  vars:
          username: ram
          password: redhat123
  tasks:
          - name: add users
            user:
                  name: "{{ username }}"
                  state: present
                  password: "{{ password | password_hash('sha512') }}"

